// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/**
 * Prisma configuration for Prisma 7.
 * Uses the direct PostgreSQL URL for migrations (extracted from the
 * prisma+postgres:// API key) to avoid proxy connection issues.
 */

function getDirectDatabaseUrl(): string {
  const url = process.env["DATABASE_URL"] || "";

  // Extract the real PostgreSQL URL from the Prisma local dev server URL
  if (url.startsWith("prisma+postgres://")) {
    try {
      const urlObj = new URL(url);
      const apiKey = urlObj.searchParams.get("api_key");
      if (apiKey) {
        const decoded = JSON.parse(
          Buffer.from(apiKey, "base64").toString("utf-8")
        );
        if (decoded.databaseUrl) {
          return decoded.databaseUrl;
        }
      }
    } catch {
      // Fall through to raw URL
    }
  }

  return url;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx ts-node prisma/seed.ts",
  },
  datasource: {
    url: getDirectDatabaseUrl(),
  },
});
